a=int(input("Enter a Value for A:"))
b=int(input("Enter a Value for B:"))
print("A =",a,"B =",b)
print("The a==b =",a==b)
print("The a>b  =",a>b)
print("The a<b =",a<b)
print("The a>=b =",a>=b)
print("The a<=b =",a<=b)
print("The a!=b =",a!=b)